name: Deploy to Railway

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SERVICE_ID: axoma
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: railway up --service=${{ env.SERVICE_ID }}
        working-directory: src/client